# Generated by Django 4.2.23 on 2025-09-19 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_date', models.DateField(blank=True, null=True)),
                ('source_url', models.CharField(blank=True, max_length=512)),
                ('source_name', models.CharField(blank=True, max_length=128)),
                ('items_total', models.PositiveIntegerField(default=0)),
                ('items_added', models.PositiveIntegerField(default=0)),
                ('items_updated', models.PositiveIntegerField(default=0)),
                ('items_marked_sold', models.PositiveIntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('centris_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('prix', models.PositiveIntegerField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('nombre_pieces', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nombre_chambres', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('nombre_sdb', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('superficie_habitable', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('superficie_terrain', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('annee_construction', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('inclus', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('proximites_text', models.TextField(blank=True)),
                ('proximites', models.JSONField(blank=True, default=list)),
                ('caracteristiques_text', models.TextField(blank=True)),
                ('caracteristiques', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SOLD', 'Sold')], default='ACTIVE', max_length=10)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen_at', '-first_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('url', models.CharField(max_length=500)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.listing')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status'], name='core_listin_status_d19315_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-last_seen_at'], name='core_listin_last_se_5c6ba6_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['-first_seen_at'], name='core_listin_first_s_ba0f74_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listingphoto',
            unique_together={('listing', 'sequence')},
        ),
    ]
