# Generated by Django 4.2.23 on 2025-09-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='agents/')),
                ('bio_short', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent / Collaborateur',
                'verbose_name_plural': 'Agents / Collaborateurs',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='core_agent_name_8d3256_idx'), models.Index(fields=['title'], name='core_agent_title_b86555_idx')],
            },
        ),
    ]
